// Cross-platform message-signing KAT generator (run manually).
//
//   cargo test -p ledger-btc-core --test kat_gen -- --ignored --nocapture
//
// Emits the canonical known-answer vectors for the message-signing corpus
// (BTC BIP-137 segwit/legacy/nested across networks + ETH EIP-191), derived
// independently in Rust from the standard BIP-39 test mnemonic. The printed
// JSON is frozen into code/test-vectors/message-signing-kat.json and asserted
// by the Rust, iOS, and Android tests, so all three implementations (and
// WalletCore on the apps) must reproduce these exact values.

use bitcoin::bip32::{DerivationPath, Xpriv};
use bitcoin::secp256k1::{Message, Secp256k1};
use bitcoin::Network;
use ledger_btc_core::{btc_sign_message, BtcMsgNetwork, BtcMsgScriptType};
use std::str::FromStr;
use tiny_keccak::{Hasher, Keccak};

// BIP-39 seed for "abandon abandon abandon abandon abandon abandon abandon
// abandon abandon abandon abandon about" with an empty passphrase (the
// canonical Trezor test vector). WalletCore's HDWallet(mnemonic) computes the
// same seed, so iOS/Android derive identical keys from the mnemonic.
const TEST_MNEMONIC: &str =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
const TEST_SEED_HEX: &str = "5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4";

const BTC_MESSAGE: &str = "Maknoon BIP-137 KAT v1";
const ETH_MESSAGE: &str = "Maknoon EIP-191 KAT v1";

fn secret_at(path: &str) -> [u8; 32] {
    let secp = Secp256k1::new();
    let seed = hex::decode(TEST_SEED_HEX).unwrap();
    let master = Xpriv::new_master(Network::Bitcoin, &seed).unwrap();
    let dp = DerivationPath::from_str(path).unwrap();
    master
        .derive_priv(&secp, &dp)
        .unwrap()
        .private_key
        .secret_bytes()
}

fn keccak256(data: &[u8]) -> [u8; 32] {
    let mut k = Keccak::v256();
    let mut out = [0u8; 32];
    k.update(data);
    k.finalize(&mut out);
    out
}

#[test]
#[ignore]
fn generate_kat_vectors() {
    let mut btc = Vec::new();
    // (script type, purpose, network enum, network label)
    let types = [
        (BtcMsgScriptType::Legacy, 44u32, "legacy"),
        (BtcMsgScriptType::NestedSegwit, 49, "nestedSegwit"),
        (BtcMsgScriptType::NativeSegwit, 84, "nativeSegwit"),
    ];
    let nets = [
        (BtcMsgNetwork::Mainnet, 0u32, "mainnet"),
        (BtcMsgNetwork::Testnet, 1, "testnet3"),
        (BtcMsgNetwork::Signet, 1, "signet"),
    ];
    for (ty, purpose, ty_label) in types {
        for (net, coin, net_label) in nets {
            let path = format!("m/{purpose}'/{coin}'/0'/0/0");
            let sk = secret_at(&path);
            let signed = btc_sign_message(sk.to_vec(), BTC_MESSAGE.to_string(), ty, net).unwrap();
            btc.push(serde_json::json!({
                "scriptType": ty_label,
                "network": net_label,
                "path": path,
                "secretKeyHex": hex::encode(sk),
                "message": BTC_MESSAGE,
                "expectedAddress": signed.address,
                "expectedSignature": signed.signature,
            }));
        }
    }

    // ETH EIP-191 personal_sign at m/44'/60'/0'/0/0.
    let secp = Secp256k1::new();
    let eth_path = "m/44'/60'/0'/0/0";
    let sk_bytes = secret_at(eth_path);
    let sk = bitcoin::secp256k1::SecretKey::from_slice(&sk_bytes).unwrap();
    let pk = bitcoin::secp256k1::PublicKey::from_secret_key(&secp, &sk);
    let uncompressed = pk.serialize_uncompressed(); // 0x04 || X || Y
    let eth_addr = {
        let h = keccak256(&uncompressed[1..]);
        format!("0x{}", hex::encode(&h[12..]))
    };
    let prefixed = {
        let m = ETH_MESSAGE.as_bytes();
        let mut v = format!("\u{0019}Ethereum Signed Message:\n{}", m.len()).into_bytes();
        v.extend_from_slice(m);
        v
    };
    let digest = keccak256(&prefixed);
    let recsig = secp.sign_ecdsa_recoverable(&Message::from_digest(digest), &sk);
    let (recid, compact) = recsig.serialize_compact();
    let v = 27u8 + (recid.to_i32() as u8);
    let mut sig = compact.to_vec();
    sig.push(v);
    let eth = serde_json::json!({
        "path": eth_path,
        "message": ETH_MESSAGE,
        "expectedAddress": eth_addr,
        "expectedSignature": format!("0x{}", hex::encode(&sig)),
    });

    let corpus = serde_json::json!({
        "_comment": "Canonical message-signing KAT. Generated by ledger-btc-core/tests/kat_gen.rs. Asserted by Rust + iOS + Android.",
        "mnemonic": TEST_MNEMONIC,
        "seedHex": TEST_SEED_HEX,
        "bitcoin": btc,
        "ethereum": eth,
    });
    println!("KAT_JSON_BEGIN");
    println!("{}", serde_json::to_string_pretty(&corpus).unwrap());
    println!("KAT_JSON_END");
}
